// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheatreHub.Data;

#nullable disable

namespace TheatreHub.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710200403_AddRolesToScenes")]
    partial class AddRolesToScenes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("TheatreHub.Models.Act", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId", "Number")
                        .IsUnique();

                    b.ToTable("Acts");
                });

            modelBuilder.Entity("TheatreHub.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("TheatreHub.Models.CharacterRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsMainRole")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId", "Name");

                    b.ToTable("CharacterRoles");
                });

            modelBuilder.Entity("TheatreHub.Models.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCurtains")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasDressingRooms")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasLighting")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasMicrophones")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasSound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasStage")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RentalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique();

                    b.ToTable("Halls");
                });

            modelBuilder.Entity("TheatreHub.Models.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PremiereDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("TheatreHub.Models.Rehearsal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("HallId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HallId");

                    b.HasIndex("PerformanceId");

                    b.HasIndex("StartDateTime");

                    b.ToTable("Rehearsals");
                });

            modelBuilder.Entity("TheatreHub.Models.RehearsalParticipant", b =>
                {
                    b.Property<int>("RehearsalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AbsenceReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("AttendanceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LateMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("RehearsalId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("RehearsalParticipants");
                });

            modelBuilder.Entity("TheatreHub.Models.RoleAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CastType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CharacterRoleId");

                    b.HasIndex("CharacterRoleId", "ActorId", "StartDate")
                        .IsUnique();

                    b.ToTable("RoleAssignments");
                });

            modelBuilder.Entity("TheatreHub.Models.Scene", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Synopsis")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActId", "Number")
                        .IsUnique();

                    b.ToTable("Scenes");
                });

            modelBuilder.Entity("TheatreHub.Models.SceneRole", b =>
                {
                    b.Property<int>("SceneId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("SceneId", "CharacterRoleId");

                    b.HasIndex("CharacterRoleId");

                    b.ToTable("SceneRoles");
                });

            modelBuilder.Entity("TheatreHub.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("TheatreHub.Models.Act", b =>
                {
                    b.HasOne("TheatreHub.Models.Performance", "Performance")
                        .WithMany("Acts")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("TheatreHub.Models.CharacterRole", b =>
                {
                    b.HasOne("TheatreHub.Models.Performance", "Performance")
                        .WithMany("CharacterRoles")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("TheatreHub.Models.Hall", b =>
                {
                    b.HasOne("TheatreHub.Models.Venue", "Venue")
                        .WithMany("Halls")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TheatreHub.Models.Rehearsal", b =>
                {
                    b.HasOne("TheatreHub.Models.Hall", "Hall")
                        .WithMany("Rehearsals")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheatreHub.Models.Performance", "Performance")
                        .WithMany("Rehearsals")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hall");

                    b.Navigation("Performance");
                });

            modelBuilder.Entity("TheatreHub.Models.RehearsalParticipant", b =>
                {
                    b.HasOne("TheatreHub.Models.Actor", "Actor")
                        .WithMany("RehearsalParticipants")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreHub.Models.Rehearsal", "Rehearsal")
                        .WithMany("Participants")
                        .HasForeignKey("RehearsalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Rehearsal");
                });

            modelBuilder.Entity("TheatreHub.Models.RoleAssignment", b =>
                {
                    b.HasOne("TheatreHub.Models.Actor", "Actor")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TheatreHub.Models.CharacterRole", "CharacterRole")
                        .WithMany("Assignments")
                        .HasForeignKey("CharacterRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("CharacterRole");
                });

            modelBuilder.Entity("TheatreHub.Models.Scene", b =>
                {
                    b.HasOne("TheatreHub.Models.Act", "Act")
                        .WithMany("Scenes")
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Act");
                });

            modelBuilder.Entity("TheatreHub.Models.SceneRole", b =>
                {
                    b.HasOne("TheatreHub.Models.CharacterRole", "CharacterRole")
                        .WithMany("SceneRoles")
                        .HasForeignKey("CharacterRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TheatreHub.Models.Scene", "Scene")
                        .WithMany("SceneRoles")
                        .HasForeignKey("SceneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterRole");

                    b.Navigation("Scene");
                });

            modelBuilder.Entity("TheatreHub.Models.Act", b =>
                {
                    b.Navigation("Scenes");
                });

            modelBuilder.Entity("TheatreHub.Models.Actor", b =>
                {
                    b.Navigation("RehearsalParticipants");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("TheatreHub.Models.CharacterRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("SceneRoles");
                });

            modelBuilder.Entity("TheatreHub.Models.Hall", b =>
                {
                    b.Navigation("Rehearsals");
                });

            modelBuilder.Entity("TheatreHub.Models.Performance", b =>
                {
                    b.Navigation("Acts");

                    b.Navigation("CharacterRoles");

                    b.Navigation("Rehearsals");
                });

            modelBuilder.Entity("TheatreHub.Models.Rehearsal", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("TheatreHub.Models.Scene", b =>
                {
                    b.Navigation("SceneRoles");
                });

            modelBuilder.Entity("TheatreHub.Models.Venue", b =>
                {
                    b.Navigation("Halls");
                });
#pragma warning restore 612, 618
        }
    }
}
